name: Validations

run-name: Validations started by @${{ github.actor }}

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  prepare-repository:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Upload node_modules as artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-modules-${{ matrix.node-version }}
          path: node_modules
          include-hidden-files: true

  run-tests:
    needs: prepare-repository
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node-modules-${{ matrix.node-version }}
          path: node_modules

      - name: Change node_modules permissions
        run: chmod -R +x node_modules/.bin

      - name: Run tests
        run: npm run test

  run-build:
    needs: prepare-repository
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node-modules-${{ matrix.node-version }}
          path: node_modules

      - name: Change node_modules permissions
        run: chmod -R +x node_modules/.bin

      - name: Run Build
        run: npm run build
